CREATE DATABASE EMPY;
USE EMPY;
CREATE TABLE EMPY(
    EID VARCHAR (4) PRIMARY KEY, 
    CONSTRAINT EMPY_EID CHECK(Length(EID)<5),
    Age INT,
    CONSTRAINT EMPY_Age CHECK (Age>17 AND Age<60),
    gender Varchar(10) NOT NULL,
    LNAme VARCHAR(50),
    CONSTRAINT EMPY_LNAme CHECK(LNAme IN (UPPER(LNAme)),
    DName VARCHAR(50),
    Salary INT,
    CONSTRAINT  EMPY_Salary CHECK(Salary > 39000 AND Salary <10001),
    phoneNo INT,
    CONSTRAINT EMPY_phoneNo UNIQUE(phoneNo),
    email VARCHAR(100),
    CONSTRAINT EMPY_email CHECK(email LIKE "%@%"),
    DOJ DATETIME default CURRENT_TIMESTAMP
);

ALTER TABLE EMPY ADD CONSTRAINT EMPY_EID2 CHECk(EID LIKE "E%");
ALTER TABLE EMPY DROP CONSTRAINT EMPY_Salary;

select CONSTRAINT_NAME, CONSTRAINT_type FROM information_schema.TABLE_CONSTRAINTS WHERE TABLE_NAME='EMPY';

INSERT INTO EMPY VALUES (
    
)